[package]
name = "nix-bindings-cpp"
version.workspace = true
edition.workspace = true

[dependencies]
nix-bindings-c = { workspace = true }

[build-dependencies]
cc = { workspace = true }
pkg-config = { workspace = true }
