[package]
name = "nix-bindings-c"
version.workspace = true
edition.workspace = true

[build-dependencies]
bindgen = { workspace = true }
doxygen-bindgen = { workspace = true }
pkg-config = { workspace = true }
